### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#195] opened 2018-06-29 10:37 UTC
**FIREFOX**

- [ ] Styling of More info on Firefox eg St. Andrews.
- [ ] No scroll on Nearest Toilets selection

**Comment by jermyk** [comment] 2018-06-29 10:38
**IE11**

**Comment by falconx** [comment] 2018-07-09 13:51
@jermyk could you explain what you mean by:
> Styling of More info on Firefox eg St. Andrews.

**Comment by Hoolean** [comment] 2018-07-16 10:34
Looks like this got closed in the pull request, though it should stay open as the Firefox scrolling issue is still at large.

To reproduce: open the toilet map in Firefox and resize the window such that the sidebar content should get its own scrollbar. Instead of this happening, the whole page is extended. This is inconsistent with other browsers.

**Closed** 2018-07-17 13:51 UTC
Labels: UI
