### ISSUE TITLE
Add new logo

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/gbptm#428] opened 2019-10-14 09:48 UTC
Domestos has asked to replace the logo with their new design:

![Use_Our_Loos_Logo_Final](https://user-images.githubusercontent.com/41140803/66742769-561d0100-ee70-11e9-8bd0-106f2af75de5.png)

## Acceptance Criteria 
- [x]  Logo works on mobile and desktop without compromising use of the site (e.g. interfering with buttons)
- [x] Logo appears as a map Icon
- [x] Logo appears on the "Use our Loos" page

## Plan
- [x] Suggest options for placement of logo
- [x] Discuss ease of implementation for each option

**Comment by HedgehogHolly** [comment] 2019-10-14 14:56
![1](https://user-images.githubusercontent.com/41140803/66761100-3ea73d80-ee9b-11e9-9efd-6bcf3736fd55.jpg)

**Comment by HedgehogHolly** [comment] 2019-10-14 14:57
![2](https://user-images.githubusercontent.com/41140803/66761115-4535b500-ee9b-11e9-8101-3e3db8e975ab.jpg)

**Comment by HedgehogHolly** [comment] 2019-10-14 14:57
![3](https://user-images.githubusercontent.com/41140803/66761129-4a92ff80-ee9b-11e9-8cb9-2d8a27ba4479.jpg)

**Comment by HedgehogHolly** [comment] 2019-10-14 14:57
![4](https://user-images.githubusercontent.com/41140803/66761141-5088e080-ee9b-11e9-95eb-a4d08d7817b5.jpg)

**Comment by charlesstrange2** [comment] 2019-10-16 09:37
We're going to try to do 
![Selection_952](https://user-images.githubusercontent.com/25037036/66907035-9612ee00-f000-11e9-9188-f25a04edb792.png)

As per @HedgehogHolly's 4th suggestion

- it doesn't take up huge amounts of space
- it floats over a non-essential bit of map
- it fits the squareness of the logo
- it doesn't reduce the current functionality by eating space for toilets
- it'll scale when then app is on a smaller screen.

Downsides

- the domestos text is a _bit_ small

**Comment by charlesstrange2** [comment] 2019-10-16 09:41
future thought: I guess we could make it clicky and pop a "sponsor" panel?

**Comment by SarikaWirtz** [comment] 2019-10-17 12:22
Here is how new logo looks like . i will make 2 PR request in a bit.

1)  
![overMap_newLogo](https://user-images.githubusercontent.com/29704252/67008264-73103900-f0e9-11e9-81d9-dc945be98775.png)

2)  
![header_newLogo](https://user-images.githubusercontent.com/29704252/67008282-7c010a80-f0e9-11e9-871d-178ec5224ac0.png)

**Comment by HedgehogHolly** [comment] 2019-10-17 13:18
Visually I definitely like the first one a lot, the only downside like Charlie said is that the domestos part is quite small.  @harryharrold do we need to send these over to them for approval?

**Comment by jermyk** [comment] 2019-10-31 15:15
## Acceptance Criteria 

Tested on  https://gbptm-stage.herokuapp.com/use-our-loosTested on 
- [x]  Logo works on mobile and desktop without compromising use of the site (e.g. interfering with buttons)
- [x] Logo appears as a map Icon
- [x] Logo appears on the "Use our Loos" page

**Desktop**
![Screenshot_103119_031046_PM](https://user-images.githubusercontent.com/4446325/67959416-9e6a4c00-fbf0-11e9-9aba-dcee75d54272.jpg)

**Android device**
![Screenshot_103119_031500_PM](https://user-images.githubusercontent.com/4446325/67959820-35cf9f00-fbf1-11e9-98f4-8bf1e8563742.jpg)
![Screenshot_103119_031524_PM](https://user-images.githubusercontent.com/4446325/67959856-43852480-fbf1-11e9-823c-384601ff0caa.jpg)

**Comment by harryharrold** [comment] 2020-03-02 14:26
@jermyk - could we try move this forward please?

**Comment by marxian** [comment] 2020-03-02 14:35
This is tricky. The placement suggested here never actually worked. I don't think Holly was really aware of how much the app changes when in a mobile-sized viewport.

**Comment by harryharrold** [comment] 2020-03-02 14:37
KK - @rachelpeharding - thoughts please!

**Comment by harryharrold** [comment] 2020-03-02 16:10
@marxian  It seems the placement in the use our loos content area in the left hand column works - the issue is with the float over the map, am I correct?

**Comment by rachelpeharding** [comment] 2020-03-02 17:14
Have had a chat with @harryharrold  suggesting we split the Use our Loos and Domestos logos (see attached). Then we can preserve the usability of the map and maintain the visibility of the logos assuming the sponsors are happy with this. 
<img width="1316" alt="GBTM solution" src="https://user-images.githubusercontent.com/61546017/75700012-54ca6480-5ca9-11ea-849a-56661052950a.png">

**Comment by harryharrold** [comment] 2020-03-03 10:51
I'd be grateful if we could:

1) Preserve the new placement of the larger size "use our loos" logo in the "use our loos" area of the "About" on the left hand side column as suggested by Holly.
2) Implement @rachelpeharding 's neatly thought-through suggestion for the siting of a smaller version.
3) Remove the problematic placement as a float on the map.
4) Get that on to staging somewhere so we can show the rest of our internal team.

When might we manage that?

**Comment by harryharrold** [comment] 2020-03-04 13:16
@jthistle - might you have a look at this?

**Comment by jthistle** [comment] 2020-03-04 16:09
Sure, will do

**Comment by marxian** [comment] 2020-03-07 12:18
Thanks @jthistle and @rachelpeharding !

I've added the UOL Logo to the info pages, and merged to `develop` so the outcome can be seen on:

https://gbptm-stage.herokuapp.com
https://gbptm-stage.herokuapp.com/use-our-loos
https://gbptm-stage.herokuapp.com/about

@harryharrold @jermyk  Let me know when it is OK to send this to production. `develop` is currently holding a very large changeset we're not ready to release yet - so when you say go I'll cherry-pick this into `master`.

**Closed** 2020-03-18 22:00 UTC
Labels: UI, enhancement

**Comment by jermyk** [comment] 2020-03-19 09:26
@marxian 

Yep looks OK, I don't see anything untoward and I can nav around the app without any issues. on desktop and mobile device (smartphone)
